CREATE VIEW [dbo].[TBLPC88] AS
select 
BRM.BARCODE AS barcode, 
stk.STOKKODU+'/'+brm.BARCODE as title,
STK.MALINCINSI+'('+LTRIM(RTRIM(STR((SELECT ISNULL(SUM(ENV.ENVANTER),0) FROM F0107D0003TBLDEPOENVANTER ENV WHERE ENV.STOKNO=STK.IND))))+')' AS description,
FORMAT((BRM.SATISFIYATI1/BRM.CARPAN)/ (SELECT ISNULL((select TOP 1 ALISFIYATI from TBLDOVIZKURU where CONVERT(date,TARIH)<=CONVERT(date,getdate()) AND DOVIZ=2 ORDER BY TARIH DESC),1)),'0.00') +' $' as price1,
FORMAT((BRM.SATISFIYATI1/BRM.CARPAN) / (SELECT ISNULL((select TOP 1 ALISFIYATI from TBLDOVIZKURU where CONVERT(date,TARIH)<=CONVERT(date,getdate()) AND DOVIZ=130 ORDER BY TARIH DESC),1)),'0.00') + ' €'
+'&#13;'+
FORMAT(BRM.SATISFIYATI1,'0.00')+' TL'
 AS Price2 from F0107TBLBIRIMLEREX BRM
INNER JOIN F0107TBLSTOKLAR STK ON BRM.STOKNO=STK.IND
where  LEN(ISNULL(BRM.BARCODE,''))>0


