--CREATE VIEW [dbo].[TBLPC88] AS
SELECT 
(SELECT 
CASE 
WHEN COUNT(STOKNO)=1 THEN (SELECT TOP 1 BARCODE FROM F0107TBLBIRIMLEREX WHERE STOKNO=S.IND AND CARPAN=1)
WHEN COUNT(STOKNO)>1 THEN (SELECT TOP 1 BARCODE FROM F0107TBLBIRIMLEREX WHERE STOKNO=S.IND AND CARPAN>1)
ELSE '' END FROM F0107TBLBIRIMLEREX WHERE STOKNO=S.IND ) AS barcode, 
S.STOKKODU+'/'+(
SELECT 
CASE 
WHEN COUNT(*)>1 THEN (SELECT TOP 1 BARCODE FROM F0107TBLBIRIMLEREX WHERE STOKNO=S.IND AND CARPAN>1)
WHEN COUNT(*)=1 THEN (SELECT TOP 1 BARCODE FROM F0107TBLBIRIMLEREX WHERE STOKNO=S.IND AND CARPAN=1)
ELSE '' END FROM F0107TBLBIRIMLEREX WHERE STOKNO=S.IND) AS title, 
S.MALINCINSI+'('+LTRIM(RTRIM(STR((SELECT ISNULL(SUM(ENV.ENVANTER),0) FROM F0107D0003TBLDEPOENVANTER ENV WHERE ENV.STOKNO=S.IND))))+')' AS description, 

--SELECT ISNULL((select TOP 1 ALISFIYATI from TBLDOVIZKURU where CONVERT(date,TARIH)<=CONVERT(date,getdate()) AND DOVIZ=2 ORDER BY TARIH DESC),1)

FORMAT(B.SATISFIYATI1/(SELECT ISNULL((select TOP 1 ALISFIYATI from TBLDOVIZKURU where CONVERT(date,TARIH)<=CONVERT(date,getdate()) AND DOVIZ=2 ORDER BY TARIH DESC),1)),'0.00') +' $' as price1,
FORMAT(B.SATISFIYATI1 / (SELECT ISNULL((select TOP 1 ALISFIYATI from TBLDOVIZKURU where CONVERT(date,TARIH)<=CONVERT(date,getdate()) AND DOVIZ=130 ORDER BY TARIH DESC),1)),'0.00') + ' €'
+'&#13;'+
FORMAT(B.SATISFIYATI1,'0.00')+' TL'

 AS Price2
FROM F0107TBLSTOKLAR AS S LEFT JOIN F0107TBLBIRIMLEREX AS B ON S.IND = B.STOKNO AND B.ANABIRIM=1
WHERE (S.STATUS <> 2) 



GO


