USE [EMELPIRLANTA]
GO

/****** Object:  View [dbo].[TBLPC88]    Script Date: 16.10.2018 13:30:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[TBLPC88] AS
SELECT 
(SELECT 
CASE 
WHEN COUNT(STOKNO)=1 THEN (SELECT TOP 1 BARCODE FROM F0113TBLBIRIMLEREX WHERE STOKNO=S.IND AND CARPAN=1)
WHEN COUNT(STOKNO)>1 THEN (SELECT TOP 1 BARCODE FROM F0113TBLBIRIMLEREX WHERE STOKNO=S.IND AND CARPAN>1)
ELSE '' END FROM F0113TBLBIRIMLEREX WHERE STOKNO=S.IND ) AS barcode, 
S.STOKKODU+'/'+(
SELECT 
CASE 
WHEN COUNT(*)>1 THEN (SELECT TOP 1 BARCODE FROM F0113TBLBIRIMLEREX WHERE STOKNO=S.IND AND CARPAN>1)
WHEN COUNT(*)=1 THEN (SELECT TOP 1 BARCODE FROM F0113TBLBIRIMLEREX WHERE STOKNO=S.IND AND CARPAN=1)
ELSE '' END FROM F0113TBLBIRIMLEREX WHERE STOKNO=S.IND) AS title, 
S.MALINCINSI+'('+LTRIM(RTRIM(STR((SELECT ISNULL(SUM(ENV.ENVANTER),0) FROM F0113D0001TBLDEPOENVANTER ENV WHERE ENV.STOKNO=S.IND))))+')' AS description, 
FORMAT(B.SATISFIYATI1 / (SELECT SATISFIYATI FROM dbo.TBLDOVIZKURU WHERE TARIH=cast(floor(cast(GETDATE() as float)) as datetime) AND (DOVIZ = 2)),'0.00') +' $' as price1,
FORMAT(B.SATISFIYATI1 / (SELECT SATISFIYATI FROM dbo.TBLDOVIZKURU WHERE TARIH=cast(floor(cast(GETDATE() as float)) as datetime) AND (DOVIZ = 130)),'0.00') + ' €'
+'&#13;'+
FORMAT(B.SATISFIYATI1 ,'0.00')+' TL'

 AS Price2
FROM F0113TBLSTOKLAR AS S LEFT JOIN F0113TBLBIRIMLEREX AS B ON S.IND = B.STOKNO AND B.ANABIRIM=1
WHERE (S.STATUS <> 2)
GO


